import Head from 'next/head';
import styles from '@/styles/Home.module.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>stock price</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>stock price</h1>
        <button
          onClick={async () => {
            const res = await fetch('/api/stock?code=8591');
            const data = await res.json();
            console.log(data);
          }}
        >
          getStock
        </button>
        <button
          onClick={async () => {
            const res = await fetch('/api/hello?code=5023');
            const data = await res.json();
            console.log(data);
          }}
        >
          Hello
        </button>
      </main>
    </>
  );
}
