import { Button, Center, Heading, VStack } from '@chakra-ui/react';
import Head from 'next/head';
import { useState } from 'react';

type Stock = {
  stockPrice: number;
  dividend: number;
};

const STOCK_CODE = '8591';
const HELLO_CODE = '5023';

export default function Home() {
  const [stockData, setStockData] = useState<Stock | null>(null);
  const [isLoadingStockData, setIsLoadingStockData] = useState<boolean>(false);

  const handleFetchStockData = async () => {
    setIsLoadingStockData(true);
    const res = await fetch(`/api/stock?code=${STOCK_CODE}`);
    const { stockPrice, dividend }: Stock = await res.json();
    setStockData({ stockPrice, dividend });
    setIsLoadingStockData(false);
  };

  const handleFetchHelloData = async () => {
    const res = await fetch(`/api/hello?code=${HELLO_CODE}`);
    const data = await res.json();
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Stock Price</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h="100vh">
        <VStack spacing={4}>
          <Heading as="h1" size="2xl">
            Stock Price
          </Heading>
          <Button
            colorScheme="blue"
            size="lg"
            isLoading={isLoadingStockData}
            loadingText="Loading..."
            onClick={handleFetchStockData}
          >
            Fetch Stock Data
          </Button>
          <Button colorScheme="green" size="lg" onClick={handleFetchHelloData}>
            Fetch Hello Data
          </Button>
          {stockData && (
            <VStack spacing={2}>
              <p>Stock Price: {stockData.stockPrice.toLocaleString()}</p>
              <p>Dividend: {stockData.dividend.toLocaleString()}</p>
            </VStack>
          )}
        </VStack>
      </Center>
    </>
  );
}
